### ISSUE TITLE
El Partido1\=Partido2 no va dentro del antecedente del forall?

### ISSUE THREAD

**Issue by natoszme** [josibuttazzoni/TP-Logico#16]
https://github.com/josibuttazzoni/TP-Logico/blob/70c30fad8ce171a34db2840f3c861b446326ec86/solucionConCambiosJosi.pl#L190

Sino se podría dar que se comparen en el consecuente dos partidos iguales y de false (porque no son distintos).

También: probar en la consola

**Comment by ezecastiglione18** [comment]
Esto en que predicado esta? Porque con las lineas que agregue no esta mas en la 190 y no se a cual te referis

**Comment by natoszme** [comment]
Si hacés click en TP-Logico/solucionConCambiosJosi.pl te lleva
