### ISSUE TITLE
Por qué ligan Partido2?

### ISSUE THREAD

**Issue by natoszme** [josibuttazzoni/TP-Logico#17]
https://github.com/josibuttazzoni/TP-Logico/blob/70c30fad8ce171a34db2840f3c861b446326ec86/solucionConCambiosJosi.pl#L184

Si lo dejan fijo antes del forall, sólo se va a comparar que se le gane a uno (el que quede ligado a Partido2)

Lo probaron en la consola? Es su amiga :stuck_out_tongue_winking_eye:

**Comment by ezecastiglione18** [comment]
Entonces es al reves? Osea, el Partido2 va al forall y el PartidoGanador en el sePostula que esta antes del forall. Es asi?

**Comment by natoszme** [comment]
Partido2 puede desaparecer de partidoGanadorProvincia si usan variable anónima
