### ISSUE TITLE
Esto dice que basta con que le gane a otro Candidate, pero no a todo el resto

### ISSUE THREAD

**Issue by natoszme** [josibuttazzoni/TP-Logico#18]
https://github.com/josibuttazzoni/TP-Logico/blob/70c30fad8ce171a34db2840f3c861b446326ec86/solucionConCambiosJosi.pl#L160

Antes tenían esto:

```
ganadorProvincia(Candidate1,Provincia):-
	esCandidate(Partido,Candidate1),
	sePostula(Partido,Provincia),
	forall(esCandidate(_,Candidate2),leGanaA(Candidate1,Candidate2,Provincia)).`
```

Por qué lo cambiaron? Me llamó la atención

Relacionado al issue #10 (revisenlo también)

**Comment by ezecastiglione18** [comment]
El 10 ya lo solucione antes. Ahora, esto lo cambio Josi porque no me acuerdo de haber cambiado mucho ese punto.

**Comment by natoszme** [comment]
Sip, como quedó ahora
