### ISSUE TITLE
No repetir logica

### ISSUE THREAD

**Issue by josibuttazzoni** [josibuttazzoni/TP-Logico#2]
https://github.com/josibuttazzoni/TP-Logico/blob/4db22dffdea926f8c8a39c771d45efef9baa0f7c/tpLogico.pl#L156

**Comment by josibuttazzoni** [comment]
@natoszme

**Comment by natoszme** [comment]
Hola! Podrían hacer un predicado que use las primeras 3 condiciones de forma genérica y que tenga una 4ta (delegando en otro predicado) definida con varias cláusulas (haciendo el "ir"). Se entiende?

**Comment by josibuttazzoni** [comment]
Sii, te habia arrobado para que vieras el resto en realidad!

Descarga Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Nato Szmedra <notifications@github.com>
Enviado: Wednesday, June 5, 2019 10:37:20 PM
Para: josibuttazzoni/TP-Logico
Cc: josibuttazzoni; Author
Asunto: Re: [josibuttazzoni/TP-Logico] No repetir logica (#2)


Hola! Podrían hacer un predicado que use las primeras 3 condiciones de forma genérica y que tenga una 4ta (delegando en otro predicado) definida con varias cláusulas (haciendo el "ir"). Se entiende?
