### ISSUE TITLE
Por qué esta cláusula no usa ambosSonCandidates?

### ISSUE THREAD

**Issue by natoszme** [josibuttazzoni/TP-Logico#6]
https://github.com/josibuttazzoni/TP-Logico/blob/f8c53b3cb56aefcaa584f178a0a7aea986e86425/tpLogico.pl#L141

A no ser que me esté perdiendo de algo, están repitiendo lógica. El enunciado dice

> El partido del ganador debe competir en la provincia

Eso tiene que cumplirse en cualquier caso! Yo lo pondría en el predicado principal (el punto de entrada para resolver este problema) y delegaría en otro que si tenga las distintas alternativas para el resto de los casos

**Comment by ezecastiglione18** [comment]
No entiendo a que te referis
