### ISSUE TITLE
Distribución del laburo

### ISSUE THREAD

**Issue by natoszme** [josibuttazzoni/TP-Logico#8]
Buenas! Este issue va menos ténico y más de cómo laburaron.
Quién hizo cada punto aprox?
Entenderán que estando desde otra compu y sólo viendo commits de uno, no me queda otra que, al menos, preguntarles!

**Comment by natoszme** [comment]
@ezecastiglione18 seguís teniendo problemas con Git?

**Comment by ezecastiglione18** [comment]
Nato! Te voy a ser honesto, no lo probé porque no tengo un rato para ver
eso. Con el tema de los parciales y finales no tuve demasiado tiempo.
Apenas pueda un rato me encargo de eso.

**Comment by natoszme** [comment]
Oka! Me interesa más la pregunta de arriba igual

**Comment by natoszme** [comment]
Oka! Me interesa más la pregunta de arriba igual

**Comment by josibuttazzoni** [comment]
Buenas! Recien leo todo. Los primeros puntos los hicimos mas o menos los dos, el 4 lo empece yo y lo siguio eze y el resto lo hice casi todo yo @natoszme
